package com.example.gitaverse.models

data class RandomShloka(
    val _id: String,
    val chapter: Int,
    val verse: Int,
    val slok: String,
    val tej: Tej,
    val siva: Siva,
    val purohit: Purohit,
    val chinmay: Chinmay,
    val abhinav: Abhinav,
    val adi: Adi,
    val anand: Anand,
    val dhan: Dhan,
    val gambir: Gambir,
    val jaya: Jaya,
    val madhav: Madhav,
    val ms: Ms,
    val neel: Neel,
    val puru: Puru,
    val raman: Raman,
    val rams: Rams,
    val san: San,
    val sankar: Sankar,
    val srid: Srid,
    val transliteration: String,
    val vallabh: Vallabh,
    val venkat: Venkat
)